apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: shakeeb2001/my-app:latest  # Ensure this is the correct image path
        imagePullPolicy: Always           # Always pull the latest image from the registry
        ports:
        - containerPort: 4000             # Port your app listens on inside the container
        env:
        - name: NODE_ENV                  # Example environment variable
          value: "production"
        resources:                        # Define resource requests and limits
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      imagePullSecrets:                   # Reference Docker registry secret
      - name: regcred                     # Ensure this secret exists in the cluster
