apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    app: my-app                     # Matches the label in the Deployment
  type: LoadBalancer                # Exposes the service externally
  ports:
  - protocol: TCP
    port: 5000                      # Port accessible externally
    targetPort: 4000                # Container's exposed port
