name: Hello World Action

on:
  push:
    branches:
      - main # This means it will run when you push to the 'main' branch

jobs:
  print-message: # The name of the job
    runs-on: ubuntu-latest # The type of server where your action will run (Ubuntu is a Linux server)

    steps:
      # Step 1: Checkout your code (always required)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Print "Hello, GitHub Actions!"
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
