name: Build and Push Docker Image

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t shakeeb2001/my-app:latest -f backend/Dockerfile backend/

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push shakeeb2001/my-app:latest
      # Step 5: Configure Kubernetes (K8s) context
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.4'

      # Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f backend/deployment.yaml
          kubectl apply -f backend/service.yaml

      # Step 7: Verify deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
